server:
  port: 80

spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:mysql://124.223.79.51:3306/iras
    username: user
    password: 8zrMdzwWiBLsPbZs
    driver-class-name: com.mysql.cj.jdbc.Driver
minio:
  url: http://124.223.79.51:9000/
  accessKey: O4MGrnU8WgK6XlPfkzjE
  secretKey: FwuCBecg4fxcS1xwTb2EPkgjtPoID32hlZ3ku988
  bucket: iras
logging:
  level:
    # trace<debug<info<warn<error<fatal
    root: info
  pattern:
    # %d{yyyy-MM-dd HH:mm:ss} [%clr(%5p)] [%thread] %clr(%logger{20}){cyan} : %msg%n
    console: "%d{yyyy-MM-dd HH:mm:ss} [%clr(%5p)] : %msg%n"
  file:
    path: "logs"